### PR TITLE
fix: add workaround to Prisma issue that hangs Node.js

### PR DESCRIPTION
**Pull request by ymc9**
In the current version, the console hangs when typing "prisma".

https://github.com/prisma/prisma/issues/18292

### CODE REVIEW

**Comment by Kinjalrk2k** [comment]
Hey! Thanks for the PR
Do you have a reproduction of the bug? I couldn't reproduce it with `@prisma/client@5.6.0`

**Comment by ymc9** [comment]
> Hey! Thanks for the PR Do you have a reproduction of the bug? I couldn't reproduce it with `@prisma/client@5.6.0`

I'm on prisma 5.6 too and it hangs right after typing "pri" 😄

repro

My steps:

- Create a project with

    ```bash
    npx try-prisma@latest -i npm -t typescript/script -p . -n repro
    cd repro
    ```

- ```npx @prismatools/console@latest```
- Try typing "prisma" in the console

**Comment by ymc9** [comment]
Btw, I'm with Mac OS and Node v18.16.0.

I'm the creator of https://github.com/zenstackhq/zenstack, and copied some code from your repo 😄.

**Comment by Kinjalrk2k** [comment]
> > Hey! Thanks for the PR Do you have a reproduction of the bug? I couldn't reproduce it with `@prisma/client@5.6.0`
> 
> I'm on prisma 5.6 too and it hangs right after typing "pri" 😄
> 
> repro
> My steps:
> 
> * Create a project with
>   ```shell
>   npx try-prisma@latest -i npm -t typescript/script -p . -n repro
>   cd repro
>   ```
> * `npx @prismatools/console@latest`
> * Try typing "prisma" in the console

## Gotcha! 

Thanks for the reproduction steps!

I confirmed that the issue persists in Node v20 too. My versions:
image

I found a funny thing! Everything works when using `await prisma.`
image

But, without the `await`, its stuck as you mentioned:
image

And the fix you made, fixes the sticking problem:
image

**Comment by Kinjalrk2k** [comment]
> Btw, I'm with Mac OS and Node v18.16.0.
> 
> I'm the creator of https://github.com/zenstackhq/zenstack, and copied some code from your repo 😄.

That's cool! ZenStack seems to be a great tool!

**Comment by Kinjalrk2k** [comment]
The fix is now live! [@prismatools/console](https://www.npmjs.com/package/@prismatools/console/v/1.1.0)

image

**Comment by ymc9** [comment]
Thank you! I got inspiration from your repo for implementing repl 😄

**Pull request merged**
